FROM node:16-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY frontend/package*.json ./

# Install dependencies
RUN npm ci

# Copy the frontend code
COPY frontend/public ./public
COPY frontend/src ./src

# Set build-time environment variable
ARG REACT_APP_API_URL=http://54.234.186.113:5001
ENV REACT_APP_API_URL=${REACT_APP_API_URL}

# Build for production
RUN npm run build

# Install serve to run the application
RUN npm install -g serve

# Expose the port
EXPOSE 3000

# Command to run the application
CMD ["serve", "-s", "build", "-l", "3000"] 